
services:
  app:
    container_name: finpay
    build:
      context: .
      dockerfile: docker/${ENVIRONMENT}/Dockerfile
      args:
        - CARGO_TARGET_DIR=/cargo-target
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - internal
    volumes:
      - .:/app:cached
      - cargo-target:/cargo-target:delegated
      - rust-cache:/usr/local/cargo/registry:delegated
    command: cargo watch -qcx run 
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s  # Wait 30 seconds before starting health checks

  postgres:
    image: postgres:15-alpine 
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "6543:5432"
    expose:
      - '6543:5432'
    networks:
      - internal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finpay.com
      PGADMIN_DEFAULT_PASSWORD: finpay
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  maildev:
    image: soulteary/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080
      MAILDEV_MAIL_DIRECTORY: "./emails"
      MAILDEV_OUTGOING_USER: finpay
      MAILDEV_OUTGOING_PASS: finpay
    networks:
      - internal
    expose:
      - 1025:1025

volumes:
  cargo-target:
  rust-cache:
  pgadmin-data:
  redis-data:
  postgres-data:

networks:
  internal:
   name: finpay_internal
